#!/bin/bash
cd /
echo "========== 水滴音樂機器人 Docker Image =========="
echo "感謝您選擇水滴音樂機器人。你剛剛啟動了一個Docker Image"
echo "這代表您已經成功安裝水滴音樂機器人了，這包括Python3自動安裝, 以及一些所需的模組"
echo "接下來，Docker將會嘗試啟動機器人"
echo "您隨時可以透過Ctrl + C強制關閉機器人，並進入本容器(Docker Container)的Ubuntu Terminal"
echo "這代表關閉機器人您並不會立刻關閉本容器，也代表您將能在關閉機器人後使用Ubuntu修改檔案"
echo "如果您不熟悉Ubuntu Terminal，請搜尋\"使用Ubuntu Bash修改檔案\"的關鍵字"
echo "nano已經預先安裝，代表你可以使用nano編輯檔案"
echo "更多資訊將會在關閉機器人後顯示!"
echo "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
echo ""
echo ""
echo "正在啟動Python..."
cd /WDMusicBot
python3.9 src/Bot.py
echo "========== 機器人已經停止 =========="
echo "剛剛機器人已經成功停止。您將進入Ubuntu Terminal (/bin/bash)"
echo "以下介紹一些編輯檔案時可能會用到的指令:"
echo "cd <資料夾名稱>                選擇資料夾"
echo "cd ..                        選擇前一個資料夾"
echo "nano <已選擇資料夾裡的檔案名稱>  編輯檔案(只限文字)"
echo "wget <連結>                   下載檔案至選擇的資料夾"
echo "ls                           查看資料夾的所有檔案名稱"
echo ""
echo "在Nano中，您可以透過Ctrl + X退出編輯器，但在退出前請Ctrl + S存檔"
echo ""
echo "機器人的檔案皆存在/WDMusicBot/，這代表您必須輸入指令: cd WDMusicBot"
echo "原始碼存在WDMusicBot，而設定檔, 存檔皆會在WDMusicBot/run"
echo ""
echo "假設今天想編輯WDMusicBot -> run -> config.json"
echo "cd WDMusicBot"
echo "cd run"
echo "nano config.json"
echo "編輯其他檔案同理。想要完整的教學請自行搜尋。"
echo ""
echo ""
echo "(如果您認為機器人不該被停止，請回報給開發者)"
echo "接下來，您將進入Ubuntu Terminal，若要重新開啟機器人，請重新啟動本Docker Container"
echo "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
echo ""
echo ""
echo ""
echo ""
bash