on:
  push:
    branches:
      - stable

name: Docker Hub Publish

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    environment: production
    steps:
    - uses: actions/checkout@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{secrets.DOCKER_ID}}
        password: ${{secrets.DOCKER_ACCESS_TOKEN}}
    - name: Build the Docker Image
      run: docker build . --file DockerFiles/Release --tag ${{secrets.DOCKER_ID}}/wd-musicbot:latest
    - name: Push the Docker Image
      run: docker push ${{secrets.DOCKER_ID}}/wd-musicbot:latest
    - name: Send message to Discord
      run: "curl -H 'Content-Type: application/json' -d '{\"content\": \"> **成功建置 Docker Image**\n立刻下載: `docker pull ${{secrets.DOCKER_ID}}/wd-musicbot:latest`\nGithub: https://github.com/fan87/wd-musicbot\"}' ${{secrets.DISCORD_WEBHOOK}}"